-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        gaps_in = 5,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "3456x2160@120.00Hz",
    position = "0x0",
    scale = 1.8,
    cm = "srgb",
})
