general {
    lock_cmd = pidof hyprlock || hyprlock       # avoids starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock screen before the system goes to sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # turns on the display after waking up
}
