
general {
    grace = 1
    # This tells hypridle what to execute when systemd says "lock"
    lock_cmd = pidof hyprlock || hyprlock
}

background {
    monitor =
	#path = screenshot   # screenshot of your desktop
	path = /home/ethanmoore/Images/Wallpaper.jpg   # NOTE only png supported for now
    #color = $color7

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_size = 5
    blur_passes = 1 # 0 disables blurring
    noise = 0.0117
    contrast = 1.3000 # Vibrant!!!
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = #2f456f
    inner_color = #5374ac
    font_color = #eff5fa
    #fade_on_empty = true
    placeholder_text = <i>Password...</i> # Text rendered in the input box when it's empty.
    hide_input = false
    
    position = 0, 200
    halign = center
    valign = bottom
}

# Date
label {
    monitor =
    text = cmd[update:18000000] echo $(date +'%A, %-d %B %Y')
    color = 0xffeff5fa
    font_size = 34
    font_family = Helvetica Neue Light 

    position = 0, -150
    halign = center
    valign = top
}



# Time
label {
    monitor =
    #text = cmd[update:1000] echo "<b><big> $(date +"%I:%M:%S %p") </big></b>" # AM/PM
    text = cmd[update:1000] echo "<big> $(date +"%H:%M:%S") </big>" # 24H
    color = 0xffeff5fa
    font_size = 94
    font_family = Helvetic Neue Bold

    position = 0, 0
    halign = center
    valign = center
}

# User
label {
    monitor =
    text =    $USER
    color = 0xff8bafd0
    font_size = 18
    font_family = Helvetica Neue Italic

    position = 0, 100
    halign = center
    valign = bottom
}

# uptime
label {
    monitor =
    text = cmd[update:60000] echo $(uptime -p || $Scripts/UptimeNixOS.sh)
    color = 0xffeff5fa
    font_size = 24
    font_family = Helvetica Neue Light
    halign = right
    valign = bottom
    position = -10, 0

}

# weather edit specific location. Note, this cause a 2-4 seconds delay in locking
label {
    monitor =
    text = cmd[update:3600000] curl -s "wttr.in/?format=4"
    color = 0xffeff5fa
    font_size = 24
    font_family = Helvetica Neue Light
    position = 10, 0
    halign = left
    valign = bottom
}

# Put a picture of choice here. Default is the current wallpaper
image {
    monitor =
    path = $HOME/.config/hypr/wallpaper_effects/.wallpaper_current
    size = 230
    rounding = -1
    border_size = 2
    border_color = $color11
    rotate = 0
    reload_time = -1
    position = 0, 300
    halign = center
    valign = bottom
}